#!/bin/bash
# =============================================================================
# SETUP.SH - Automated Infrastructure & K8s Setup (Linux/Mac)
# =============================================================================
# Chạy: chmod +x setup.sh && ./setup.sh
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() { echo -e "\n${BLUE}=============================================${NC}\n${BLUE}$1${NC}\n${BLUE}=============================================${NC}\n"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }

# =============================================================================
# LOAD .ENV FILE
# =============================================================================
print_header "1. Đọc cấu hình từ .env"

if [ ! -f ".env" ]; then
    print_error "Không tìm thấy file .env!"
    echo "Hãy copy .env.example thành .env và điền thông tin."
    exit 1
fi

# Load .env
export $(grep -v '^#' .env | xargs)

# Validate required vars
if [ -z "$AWS_KEY_NAME" ] || [ "$AWS_KEY_NAME" = "your-key-name-here" ]; then
    print_error "AWS_KEY_NAME chưa được cấu hình trong .env"
    exit 1
fi

print_success "AWS_KEY_NAME: $AWS_KEY_NAME"

# Check SSH key file
SSH_KEY_PATH="${AWS_KEY_NAME}.pem"
if [ ! -f "$SSH_KEY_PATH" ]; then
    print_error "Không tìm thấy SSH key: $SSH_KEY_PATH"
    exit 1
fi
print_success "SSH Key file: $SSH_KEY_PATH"

# =============================================================================
# PRE-FLIGHT CHECKS
# =============================================================================
print_header "2. Kiểm tra prerequisites"

if ! command -v terraform &> /dev/null; then
    print_error "Terraform chưa được cài đặt!"
    exit 1
fi
print_success "Terraform: $(terraform version -json | grep -o '"terraform_version":"[^"]*"' | cut -d'"' -f4)"

if ! command -v ansible &> /dev/null; then
    print_error "Ansible chưa được cài đặt!"
    exit 1
fi
print_success "Ansible: $(ansible --version | head -n1)"

# =============================================================================
# TERRAFORM
# =============================================================================
print_header "3. Terraform - Tạo Infrastructure"

cd terraform

terraform init -upgrade
terraform plan -var="key_name=$AWS_KEY_NAME" -out=tfplan
terraform apply tfplan

# Get outputs
K8S_IP=$(terraform output -raw k8s_master_public_ip)
SONARQUBE_IP=$(terraform output -raw sonarqube_public_ip)
K8S_PRIVATE_IP=$(terraform output -raw k8s_master_private_ip)

print_success "K8s Master IP: $K8S_IP"
print_success "SonarQube IP: $SONARQUBE_IP"

cd ..

# =============================================================================
# GENERATE ANSIBLE INVENTORY
# =============================================================================
print_header "4. Tạo Ansible Inventory"

cat > ansible/inventory/hosts.ini << EOF
# Auto-generated by setup.sh at $(date)

[k8s_master]
k8s-master ansible_host=${K8S_IP} ansible_user=ubuntu ansible_ssh_private_key_file=../${SSH_KEY_PATH}

[k8s_master:vars]
ansible_python_interpreter=/usr/bin/python3
k8s_master_private_ip=${K8S_PRIVATE_IP}

[sonarqube]
sonarqube ansible_host=${SONARQUBE_IP} ansible_user=ubuntu ansible_ssh_private_key_file=../${SSH_KEY_PATH}

[sonarqube:vars]
ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
EOF

print_success "Inventory đã được tạo"

# =============================================================================
# WAIT FOR SSH
# =============================================================================
print_header "5. Đợi servers sẵn sàng"

echo "Đang đợi SSH ready..."
for i in {1..30}; do
    if ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -i "$SSH_KEY_PATH" ubuntu@"$K8S_IP" "echo 'OK'" &>/dev/null; then
        print_success "K8s Master SSH ready!"
        break
    fi
    echo "Đợi... ($i/30)"
    sleep 10
done

# =============================================================================
# RUN ANSIBLE
# =============================================================================
print_header "6. Ansible - Cấu hình K8s Cluster"

cd ansible
ansible all -i inventory/hosts.ini -m ping
ansible-playbook -i inventory/hosts.ini playbooks/k8s-master.yml
cd ..

# =============================================================================
# SUMMARY
# =============================================================================
print_header "🎉 SETUP HOÀN TẤT!"

echo -e "${GREEN}"
cat << EOF
=============================================
           THÔNG TIN HỆ THỐNG
=============================================

📦 K8s Master Node:
   - IP: $K8S_IP
   - SSH: ssh -i $SSH_KEY_PATH ubuntu@$K8S_IP

🔍 SonarQube Server:
   - URL: http://$SONARQUBE_IP:9000
   - Login: admin / admin

=============================================
EOF
echo -e "${NC}"
