# =============================================================================
# SETUP.PS1 - Automated Infrastructure & K8s Setup (Windows PowerShell)
# =============================================================================
# Chạy: .\setup.ps1
# =============================================================================

$ErrorActionPreference = "Stop"

function Write-Header { param([string]$Message); Write-Host "`n=============================================`n$Message`n=============================================`n" -ForegroundColor Blue }
function Write-Success { param([string]$Message); Write-Host "✅ $Message" -ForegroundColor Green }
function Write-Error { param([string]$Message); Write-Host "❌ $Message" -ForegroundColor Red }

# =============================================================================
# LOAD .ENV FILE
# =============================================================================
Write-Header "1. Đọc cấu hình từ .env"

if (-not (Test-Path ".env")) {
    Write-Error "Không tìm thấy file .env!"
    Write-Host "Hãy copy .env.example thành .env và điền thông tin."
    exit 1
}

# Load .env
Get-Content ".env" | ForEach-Object {
    if ($_ -match "^\s*([^#][^=]+)=(.*)$") {
        $name = $matches[1].Trim()
        $value = $matches[2].Trim()
        Set-Variable -Name $name -Value $value -Scope Script
    }
}

if ([string]::IsNullOrEmpty($AWS_KEY_NAME) -or $AWS_KEY_NAME -eq "your-key-name-here") {
    Write-Error "AWS_KEY_NAME chưa được cấu hình trong .env"
    exit 1
}
Write-Success "AWS_KEY_NAME: $AWS_KEY_NAME"

$sshKeyPath = "$AWS_KEY_NAME.pem"
if (-not (Test-Path $sshKeyPath)) {
    Write-Error "Không tìm thấy SSH key: $sshKeyPath"
    exit 1
}
Write-Success "SSH Key file: $sshKeyPath"

# =============================================================================
# PRE-FLIGHT CHECKS
# =============================================================================
Write-Header "2. Kiểm tra prerequisites"

try {
    $tfVersion = terraform version -json | ConvertFrom-Json
    Write-Success "Terraform: $($tfVersion.terraform_version)"
} catch {
    Write-Error "Terraform chưa được cài đặt!"
    exit 1
}

# Check Ansible (WSL)
$wslAnsible = wsl which ansible 2>$null
if ($null -eq $wslAnsible) {
    Write-Error "Ansible chưa được cài đặt trong WSL!"
    Write-Host "Cài đặt: wsl sudo apt install ansible"
    exit 1
}
Write-Success "Ansible: (WSL)"

# =============================================================================
# TERRAFORM
# =============================================================================
Write-Header "3. Terraform - Tạo Infrastructure"

Set-Location terraform

terraform init -upgrade
terraform plan -var="key_name=$AWS_KEY_NAME" -out=tfplan
terraform apply tfplan

$K8S_IP = terraform output -raw k8s_master_public_ip
$SONARQUBE_IP = terraform output -raw sonarqube_public_ip
$K8S_PRIVATE_IP = terraform output -raw k8s_master_private_ip

Write-Success "K8s Master IP: $K8S_IP"
Write-Success "SonarQube IP: $SONARQUBE_IP"

Set-Location ..

# =============================================================================
# GENERATE ANSIBLE INVENTORY
# =============================================================================
Write-Header "4. Tạo Ansible Inventory"

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
@"
# Auto-generated by setup.ps1 at $timestamp

[k8s_master]
k8s-master ansible_host=$K8S_IP ansible_user=ubuntu ansible_ssh_private_key_file=../$sshKeyPath

[k8s_master:vars]
ansible_python_interpreter=/usr/bin/python3
k8s_master_private_ip=$K8S_PRIVATE_IP

[sonarqube]
sonarqube ansible_host=$SONARQUBE_IP ansible_user=ubuntu ansible_ssh_private_key_file=../$sshKeyPath

[sonarqube:vars]
ansible_python_interpreter=/usr/bin/python3

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
"@ | Out-File -FilePath "ansible\inventory\hosts.ini" -Encoding UTF8

Write-Success "Inventory đã được tạo"

# =============================================================================
# WAIT FOR SSH
# =============================================================================
Write-Header "5. Đợi servers sẵn sàng"

Write-Host "Đang đợi SSH ready..."
for ($i = 1; $i -le 30; $i++) {
    try {
        $result = ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -i $sshKeyPath ubuntu@$K8S_IP "echo 'OK'" 2>$null
        if ($result -eq "OK") {
            Write-Success "K8s Master SSH ready!"
            break
        }
    } catch { }
    Write-Host "Đợi... ($i/30)"
    Start-Sleep -Seconds 10
}

# =============================================================================
# RUN ANSIBLE (via WSL)
# =============================================================================
Write-Header "6. Ansible - Cấu hình K8s Cluster"

Set-Location ansible
wsl ansible all -i inventory/hosts.ini -m ping
wsl ansible-playbook -i inventory/hosts.ini playbooks/k8s-master.yml
Set-Location ..

# =============================================================================
# SUMMARY
# =============================================================================
Write-Header "🎉 SETUP HOÀN TẤT!"

Write-Host @"

=============================================
           THÔNG TIN HỆ THỐNG
=============================================

📦 K8s Master Node:
   - IP: $K8S_IP
   - SSH: ssh -i $sshKeyPath ubuntu@$K8S_IP

🔍 SonarQube Server:
   - URL: http://${SONARQUBE_IP}:9000
   - Login: admin / admin

=============================================

"@ -ForegroundColor Green
